global:
  smtp_smarthost: 
  smtp_from: 
  smtp_auth_username: 
  smtp_auth_password: 
  smtp_require_tls: true

route:
  receiver: 'email-notifications'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 
        send_resolved: true
